<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>

			<h2 class="font18 fb">广东盐业监管-追溯对接接口协议标准</h2>
			<p class="mt30 mb10 font16">1、数据流向</p>
			<p class="">下图是数据从溯源到监管平台到省平台的流向及处理步骤，有助于开发员了解数据流向。</p>
			<div class="helpimg-div">
				<img src="${ctx}/static/images/helpcenter/dataflow_1.jpg" alt=""/>
				<img src="${ctx}/static/images/helpcenter/dataflow_2.jpg" alt=""/>
			</div>
			<div>
				<div class="mt10 mb10">说明</div>
				<ul class="help-flowtip">
					<li>1.溯源上传数据到监管平台</li>
					<li>2.监管平台接收到数据，做初步校验，如果存在数据不合格，拒绝接收；如果数据初步校验没问题，则收入到日志表，返回告诉溯源监管平台接收成功</li>
					<li>3.监管平台定时从日志表中把溯源上传的数据拿出来，进一步校验，如果数据合格，则入库，等待上报省平台</li>
					<li>4.监管平台定时把等待上报省平台的数据拿出来，上传给省平台，把省平台接收结果记录下来</li>
					<li>5.监管平台定时将已上传成功到省平台的数据记录拿出来，向省平台发出查询，查询省平台对数据的处理结果</li>
					<li>1.溯源向监管平台发起查询，监管平台告诉溯源方，监管平台和省平台对数据的处理结果</li>
				</ul>
			</div>
			<p class="mt30 mb10 font16">2、数据上报</p>
			<p class="">接口协议采取的是restFull方式，数据格式是json格式。测试地址：http://test.apigdsaltreportservice.api.salt.qhgrain.com</p>
			<div class="help-interface">
			<p>2.1、上报接口说明</p>
			<table class="table data-table table-bordered table-fixed mt10">
				<tr>
					<td class="ds-bg-gray text-right" width="100px">url</td>
					<td class="text-left pl10">ip或域名/1.0/trace/data/upload</td>	
				</tr>
				<tr>
					<td class="ds-bg-gray text-right">请求方式</td>
					<td class="text-left pl10">post</td>	
				</tr>
				<tr>
					<td class="ds-bg-gray text-right" >MediaType</td>
					<td class="text-left pl10">application/x-www-form-urlencoded</td>	
				</tr>
				<tr>
					<td class="ds-bg-gray text-right">参数</td>
					<td class="text-left pl10">jsonData / json字符串</td>	
				</tr>
				<tr>
					<td colspan="2" class="text-left p20">
					{   <br/>
					    "dataFromSys":"数据来源哪个系统",<br/>
					    "sysAccount":"在省平台注册的账号",<br/>
					    "sysApiKey":"加密账号，省平台获取，数据上报省时需用到",<br/>
					    "sysApiSecret":"密钥，省平台获取，数据上报省时需用到",<br/>
					    "documentId":"文档id，唯一性，是此次提交的标识号，便于后续根据该文档id查询该次批量提交的上报情况",<br/>
					    "dataType":"数据类型",<br/>
					    "dataList":[{
					        }]<br/>
					}
					</td>
				</tr>
			</table>
			
			<p>字段说明</p>
			<table class="table table-horizontal table-border table-fixed mt10">
				<tr>
					<th>中文名称</th>
					<th>英文名称</th>
					<th>类型</th>
					<th>长度</th>
					<th>是否非必填</th>
					<th width='300px'>说明</th>
				</tr>
				<tr>
					<td>数据来源</td>
					<td>dataFromSys</td>
					<td>string</td>	
					<td>100</td>	
					<td>必填</td>	
					<td></td>		
				</tr>
				<tr>
					<td>账号</td>
					<td>sysAccount</td>
					<td></td>	
					<td></td>	
					<td></td>	
					<td>在省平台注册的账号</td>		
				</tr>
				<tr>
					<td>加密账号</td>
					<td>sysApiKey</td>
					<td>string</td>	
					<td>100</td>	
					<td>必填</td>	
					<td>向省平台获取</td>		
				</tr>
				<tr>
					<td>密钥</td>
					<td>sysApiSecret</td>
					<td>string</td>	
					<td>100</td>	
					<td>必填</td>	
					<td>向省平台获取</td>		
				</tr>
				<tr>
					<td>文档id</td>
					<td>documentId</td>
					<td>string</td>	
					<td>50</td>	
					<td>必填</td>	
					<td>文档id，唯一性，是此次提交的标识号，便于后续根据该文档id查询该次批量提交的上报情况</td>		
				</tr>
				<tr>
					<td>数据类型</td>
					<td>dataType</td>
					<td>string</td>	
					<td>50</td>	
					<td>必填</td>	
					<td>说明此次上传的数据是什么数据。具体看后面数据表</td>		
				</tr>
				<tr>
					<td>详细数据</td>
					<td>dataList</td>
					<td>text</td>	
					<td>50</td>	
					<td>必填</td>	
					<td>具体看后面的数据表</td>		
				</tr>
				<tr>
					<td class="text-left">返回结果：上传成功</td>
					<td colspan='5' class="text-left">
						{<br/>
						    "state":"1001",<br/>
						    "stateMsg":"上传到监管平台成功,正在校验数据进行入库",<br/>
						    "errorCode":"",<br/>
						    "errorMsg":""<br/>
						}
					</td>
				</tr>
				<tr>
					<td class="text-left">返回结果：上传失败</td>
					<td colspan='5' class="text-left">
					{<br/>
					    "state":"1002",<br/>
					    "stateMsg":"上传到监管平台失败",<br/>
					    "errorCode":"?",<br/>
					    "errorMsg":"?"<br/>
					}
					</td>
				</tr>
			</table>
			</div>
			<p class="mt10">失败说明：<br/>errorCode:失败原因对应的编码.errorMsg:失败原因的详细信息.</p>
			<div class="mt10">上传时，反馈的错误码
			<table class="table table-horizontal table-border table-fixed mt10">
				<tr>
					<th>errorCode</th>
					<th>errorMsg</th>
				</tr>
				<tr>
					<td>1005</td>
					<td>documentId不能为空且长度不能超过50</td>
				</tr>
				<tr>
					<td>1006</td>
					<td>documentId已存在，请确保唯一性</td>
				</tr>
				<tr>
					<td>1007</td>
					<td>documentId不存在,请检查</td>
				</tr>
				<tr>
					<td>1008</td>
					<td>上传时参数jsonData不能为空</td>
				</tr>
				<tr>
					<td>1009</td>
					<td>请检查数据格式是否是json格式</td>
				</tr>
				<tr>
					<td>1010</td>
					<td>dataFromSys数据来源不能为空且长度不能超过100</td>
				</tr>
				<tr>
					<td>1011</td>
					<td>sysAccount平台账号不能为空且长度不能超过100</td>
				</tr>
				<tr>
					<td>1012</td>
					<td>sysApiKey加密账号不能为空且长度不能超过100</td>
				</tr>
				<tr>
					<td>1013</td>
					<td>sysApiSecret密钥不能为空且长度不能超过100</td>
				</tr>
				<tr>
					<td>1014</td>
					<td>上传的数据类型不能为空或不存在</td>
				</tr>
				<tr>
					<td>1015</td>
					<td>不存在记录！请检查sysApiKey和documentId是否完全正确！</td>
				</tr>
				<tr>
					<td>1016</td>
					<td>dataList详细数据不能为空或总数不能超过100</td>
				</tr>
				<tr>
					<td>1017</td>
					<td>将dataList转为javaBean失败，请检查dataList的数据是否正确且和dataType对应!</td>
				</tr>
				<tr>
					<td>1018</td>
					<td>上报的数据中存在不合格的数据！</td>
				</tr>
				<tr>
					<td>9999</td>
					<td>监管平台系统错误，请联系监管平台!</td>
				</tr>
				
			</table>
			</div>
			<p>2.2、查询接口说明</p>
			<table class="table data-table table-bordered table-fixed mt10">
				<tr>
					<td class="ds-bg-gray text-right" width="100px">url</td>
					<td class="text-left pl10">ip或域名/1.0/trace/data/queryUploadState</td>	
				</tr>
				<tr>
					<td class="ds-bg-gray text-right">请求方式</td>
					<td class="text-left pl10">post</td>	
				</tr>
				<tr>
					<td class="ds-bg-gray text-right" >MediaType</td>
					<td class="text-left pl10">application/x-www-form-urlencoded</td>	
				</tr>
				<tr>
					<td class="ds-bg-gray text-right">参数</td>
					<td class="text-left pl10">jsonData / json字符串</td>	
				</tr>
				<tr>
					<td colspan="2" class="text-left p20">
					{<br/>
					    "sysApiKey":"加密账号",<br/>
					    "documentId":"文档id，查询该文档id对应的提交批次的数据处理情况"<br/>
					}
					</td>
				</tr>
				<tr>
					<td colspan="2" class="text-left p20">
					返回结果:<br/>
					{<br/>
					    "state":"记录目前的状态",<br/>
					    "stateMsg":"状态说明！",<br/>
					    "errorCode":"",<br/>
					    "errorMsg":""<br/>
					}

					</td>
				</tr>
			</table>
			<div class="mt10">上传时，反馈的错误码
			    <table class="table table-horizontal table-border table-fixed mt10">
					<tr>
						<th>errorCode</th>
						<th>errorMsg</th>
					</tr>
					<tr>
						<td>1001</td>
						<td>上传到监管平台成功,正在校验数据进行入库</td>
					</tr>
					<tr>
						<td>1003</td>
						<td>数据保存进监管平台成功,等待上传省平台</td>
					</tr>
					<tr>
						<td>1019</td>
						<td>监管平台对数据深层次校验，数据不合格</td>
					</tr>
					<tr>
						<td>1004</td>
						<td>监管平台异步将数据保存入库时系统错误，请联系监管平台!</td>
					</tr>
					<tr>
						<td>2001</td>
						<td>无法登录省平台</td>
					</tr>
					<tr>
						<td>2002</td>
						<td>上传到省平台成功，省平台	处理中</td>
					</tr>
					<tr>
						<td>2003</td>
						<td>上报省平台时监管平台系统出错!请联系监管平台！</td>
					</tr>
					<tr>
						<td>2004</td>
						<td>上传到省平台失败，数据无法通过省平台初步检查</td>
					</tr>
					<tr>
						<td>3000</td>
						<td>省平台数据入库成功</td>
					</tr>
					<tr>
						<td>3001</td>
						<td>数据无法通过省平台深层次校验！</td>
					</tr>
					<tr>
						<td>3002</td>
						<td>省平台处理数据时系统错误，请联系省平台！</td>
					</tr>
				</table>
	 		 </div>
	<p class="font16 mt10 mb10">3.非乳粉食品数据上报</p>
	<p>3.1生产企业</p>
	<p>a) 原料购进信息（ProductMaterialBuy）</p>
	<table class="table table-horizontal table-border table-fixed mt10">
		<tr>
			<th>中文名称</th>
			<th>英文名称</th>
			<th>类型</th>
			<th>长度</th>
			<th>是否必填</th>
			<th width='300px'>说明</th>
		</tr>
		<tr>
			<td>流水号</td>
			<td>originNo</td>
			<td>string</td>
			<td>100</td>
			<td>必填</td>
			<td>就是该记录的id</td>
		</tr>
		<tr>
			<td>进货日期</td>
			<td>purchaseDate</td>
			<td>string</td>
			<td></td>
			<td>必填</td>
			<td>格式：yyyy-mm-dd</td>
		</tr>
		<tr>
			<td>供货商名称</td>
			<td>supplier</td>
			<td>string</td>
			<td>50</td>
			<td>必填</td>
			<td></td>
		</tr>
		<tr>
			<td>密钥</td>
			<td>sysApiSecret</td>
			<td>string</td>
			<td>100</td>
			<td>必填</td>
			<td>向省平台获取</td>
		</tr>
		<tr>
			<td>原料名称</td>
			<td>materialName</td>
			<td>string</td>
			<td>50</td>
			<td>必填</td>
			<td></td>
		</tr>
		<tr>
			<td>原料批次</td>
			<td>manufacturer</td>
			<td>string</td>
			<td>255</td>
			<td>必填</td>
			<td></td>
		</tr>
		<tr>
			<td>规格</td>
			<td>specifName</td>
			<td>text</td>
			<td>50</td>
			<td>必填</td>
			<td></td>
		</tr>
	<tr>
	<td>保质期</td>
	<td>qualityPeriod</td>
	<td>text</td>
	<td>50</td>
	<td>必填</td>
	<td></td>
	</tr>
	<tr>
	<td>生产日期</td>
	<td>produceDate</td>
	<td>date</td>
	<td>50</td>
	<td>必填</td>
	<td>格式：yyyy-mm-dd</td>
	</tr>
	<tr>
	<td>地址</td>
	<td>place</td>
	<td>string</td>
	<td>255</td>
	<td>必填</td>
	<td></td>
	</tr>
	<tr>
	<td>联系电话</td>
	<td>phoneNo</td>
	<td>string</td>
	<td>50</td>
	<td>必填</td>
	<td></td>
	</tr>
	<tr>
	<td>进货数量</td>
	<td>total</td>
	<td>integer</td>
	<td></td>
	<td>必填</td>
	<td></td>
	</tr>
	<tr>
	<td>包装单位</td>
	<td>unit</td>
	<td>string</td>
	<td>50</td>
	<td>必填</td>
	<td>参见附录小包装单位</td>
	</tr>
	<tr>
	<td>食盐辅料</td>
	<td>saltMaterials</td>
	<td>string</td>
	<td>255</td>
	<td>必填</td>
	<td></td>
	</tr>
	<tr>
	<td>原料检测报告文件名称</td>
	<td>checkReportFileName</td>
	<td>string</td>
	<td>50</td>
	<td>必填</td>
	<td>上传文件名称（界面显示用），请加上文件的后缀，比如.pdf</td>
	</tr>
	<tr>
	<td>原料检测报告文件</td>
	<td>checkReportFile</td>
	<td>text</td>
	<td></td>
	<td>必填</td>
	<td>将pdf文件进行base64编码，变成字符串，便于传输，文件大小，小于等于300K</td>
	</tr>

			<tr>
			<td colspan='6' class="text-left">
				{<br/>
				"dataFromSys":"数据来源哪个系统",<br/>
				"sysAccount":"账号",<br/>
				"sysApiKey":"加密账号",<br/>
				"sysApiSecret":"密钥",<br/>
				"documentId":"文档id，唯一性，是此次提交的标识号，便于后续根据该文档id查询该次批量提交的上报情况",<br/>
				"dataType":"ProductMaterialBuy",<br/>
				"dataList":[
				{<br/>
				"originNo":"记录的流水号，也就是该记录的id",<br/>
				"purchaseDate":"进货日期yyyy-MM-dd",<br/>
				"supplier":"供应商名称",<br/>
				"materialName":"原料名称",<br/>
				"batch":"原料批次",<br/>
				"manufacturer":"原料生产厂家",<br/>
				"specifName":"规格",<br/>
				"qualityPeriod":"保质期",<br/>
				"produceDate":"生产日期yyyy-MM-dd",<br/>
				"place":"地址",<br/>
				"phoneNo":"联系电话",<br/>
				"total":"进货数量",<br/>
				"unit":"包装单位",<br/>
				"saltMaterials":"食盐辅料",<br/>
				"checkReportFileName":"原料检测报告文件名称",<br/>
				"checkReportFile":"原料检测报告文件"<br/>
				}
				]
				}
			</td>
		</tr>
	</table>

	<p class="font16 mt20 mb10">b) 1. 产品生产追溯信息-产品生产信息（ProduceInfo）</p>
	<table class="table table-horizontal table-border table-fixed mt10">
	<tr>
	<th>中文名称</th>
	<th>英文名称</th>
	<th>类型</th>
	<th>长度</th>
	<th>是否必填</th>
	<th width='300px'>说明</th>
	</tr>
	<tr>
	<td>流水号</td>
	<td>originNo</td>
	<td>string</td>
	<td>100</td>
	<td>必填</td>
	<td>记录的id</td>
	</tr>
	<tr>
	<td>条形码</td>
	<td>productBarCode</td>
	<td>string</td>
	<td>50</td>
	<td>必填</td>
	<td>按国际标准编制的产品条形码</td>
	</tr>
	<tr>
	<td>生产批次</td>
	<td>batch</td>
	<td>string</td>
	<td>50</td>
	<td>非必填</td>
	<td>产品的生产批次</td>
	</tr>
	<tr>
	<td>生产日期</td>
	<td>produceDate</td>
	<td>string</td>
	<td></td>
	<td>必填</td>
	<td>格式：yyyy-mm-dd</td>
	</tr>
	<tr>
	<td>生产数量</td>
	<td>total</td>
	<td>integer</td>
	<td></td>
	<td>必填</td>
	<td></td>
	</tr>
	<tr>
	<td>计量单位</td>
	<td>measurementUnit</td>
	<td>string</td>
	<td>50</td>
	<td>必填</td>
	<td>参见附录小包装单位
	</td>
	</tr>
	<tr>
	<td>箱码</td>
	<td>boxCode</td>
	<td>string</td>
	<td>50</td>
	<td>两个必填一个</td>
	<td>符合以下规则的产品购进需上报箱码：
	按箱进货
	</td>
	</tr>
	<tr>
	<td>追溯码</td>
	<td>traceCode</td>
	<td>string</td>
	<td>50</td>
	<td>必填</td>
	<td>符合以下规则的产品购进需上报追溯码：
	按最小包装(如：罐)进货
	</td>
	</tr>
	<tr>
	<td>生产企业名称</td>
	<td>produceEnterprise</td>
	<td>string</td>
	<td>50</td>
	<td>必填</td>
	<td>产品的生产企业</td>
	</tr>
	<tr>
	<td>产品名称</td>
	<td>produceName</td>
	<td>string</td>
	<td>50</td>
	<td>必填</td>
	<td></td>
	</tr>
	<tr>
	<td>规格</td>
	<td>spec</td>
	<td>string</td>
	<td>50</td>
	<td>非必填</td>
	<td></td>
	</tr>
	<tr>
	<td>类别</td>
	<td>category</td>
	<td>string</td>
	<td>50</td>
	<td>非必填</td>
	<td></td>
	</tr>
	<tr>
	<td>包装单位</td>
	<td>unit</td>
	<td>string</td>
	<td>50</td>
	<td>必填</td>
	<td></td>
	</tr>
	<tr>
	<td>品牌</td>
	<td>brand</td>
	<td>string</td>
	<td>50</td>
	<td>必填</td>
	<td></td>
	</tr>
	<tr>
	<td>包装	</td>
	<td>packingVal</td>
	<td>String	</td>
	<td>50</td>
	<td>非必填</td>
	<td></td>
	</tr>
	<tr>
	<td>保质期</td>
	<td>overdueVal</td>
	<td>string</td>
	<td>50</td>
	<td>非必填</td>
	<td></td>
	</tr>
	<tr>
	<td>产品二维码</td>
	<td>qrCode</td>
	<td>string</td>
	<td>50</td>
	<td>必填</td>
	<td></td>
	</tr>
	<tr>
	<td>产品名称 </td>
	<td>productName</td>
	<td>string</td>
	<td>50</td>
	<td>非必填</td>
	<td>产品的名称</td>
	</tr>
	<tr>
	<td>生产许可证编号</td>
	<td>producePermitNumber</td>
	<td>string</td>
	<td>50</td>
	<td>非必填</td>
	<td>生产许可证编号</td>
	</tr>

	<tr>
	<td colspan='6' class="text-left">
	{<br/>
	"dataFromSys":"数据来源哪个系统",<br/>
	"sysAccount":"账号",<br/>
	"sysApiKey":"加密账号",<br/>
	"sysApiSecret":"密钥",<br/>
	"documentId":"文档id，唯一性，是此次提交的标识号，便于后续根据该文档id查询该次批量提交的上报情况",<br/>
	"dataType":"ProduceInfo",<br/>
	"dataList":[<br/>
	{<br/>
	"originNo":"记录的流水号，也就是该记录的id",<br/>
	"productBarCode":"产品条形码",<br/>
	"batch":"生产批次",<br/>
	"produceDate":"生产日期",<br/>
	"total":"生产数量",<br/>
	"measurementUnit":"计量单位",<br/>
	"boxCode":"箱码",<br/>
	"traceCode":"追溯码",<br/>
	"produceEnterprise":"生产企业名称",<br/>
	"produceAddress":"生产企业地址",<br/>
	"produceName":"产品名称",<br/>
	"spec":"规格",<br/>
	"category":"类别",<br/>
	"brand":"品牌",<br/>
	"packingVal":"包装",
	"overdueVal":"保质期",<br/>
	"qrCode":"产品二维码"，<br/>
	"productName":"产品名称",<br/>
	"producePermitNumber":"生产许可证编号"<br/>
	}
	]
	}
	</td>
	</tr>
	</table>
	<p class="font16 mt20 mb10">b) 2. 产品生产追溯信息-产品包装信息（ProductPackInfo）</p>
	<table class="table table-horizontal table-border table-fixed mt10">
	<tr>
	<th>中文名称</th>
	<th>英文名称</th>
	<th>类型</th>
	<th>长度</th>
	<th>是否必填</th>
	<th width='300px'>说明</th>
	</tr>
	<tr>
	<td>流水号</td>
	<td>originNo</td>
	<td>string</td>
	<td>100</td>
	<td>必填</td>
	<td>记录的id</td>
	</tr>
	<tr>
	<td>条形码</td>
	<td>productBarCode</td>
	<td>string</td>
	<td>50</td>
	<td>必填</td>
	<td>按国际标准编制的产品条形码</td>
	</tr>
	<tr>
	<td>生产批次</td>
	<td>batch</td>
	<td>string</td>
	<td>50</td>
	<td>非必填</td>
	<td>产品的生产批次</td>
	</tr>
	<tr>
	<td>生产日期</td>
	<td>createDate</td>
	<td>string</td>
	<td></td>
	<td>非必填</td>
	<td>格式：yyyy-mm-dd</td>
	</tr>

	<tr>
	<td>箱码</td>
	<td>boxQrCode</td>
	<td>string</td>
	<td>50</td>
	<td>两个必填一个</td>
	<td>符合以下规则的产品购进需上报箱码：
	按箱进货
	</td>
	</tr>
	<tr>
	<td>追溯码</td>
	<td>traceCode</td>
	<td>string</td>
	<td>50</td>
	<td>必填</td>
	<td>符合以下规则的产品购进需上报追溯码：
	按最小包装(如：罐)进货
	</td>
	</tr>
	<tr>
	<td>虚拟箱码	</td>
	<td>vBoxQrCode</td>
	<td>string</td>
	<td>50</td>
	<td>非必填</td>
	<td></td>
	</tr>
	<tr>
	<td>工厂	</td>
	<td>factory</td>
	<td>string</td>
	<td>255</td>
	<td>非必填</td>
	<td></td>
	</tr>
	<tr>
	<td>产线	</td>
	<td>station</td>
	<td>string</td>
	<td>50</td>
	<td>非必填</td>
	<td></td>
	</tr>
	<tr>
	<td>班次	</td>
	<td>shift</td>
	<td>string</td>
	<td>50</td>
	<td>非必填</td>
	<td></td>
	</tr>
	<tr>
	<td colspan='6' class="text-left">
	{<br/>
	"dataFromSys":"数据来源哪个系统",<br/>
	"sysAccount":"账号",<br/>
	"sysApiKey":"加密账号",<br/>
	"sysApiSecret":"密钥",<br/>
	"documentId":"文档id，唯一性，是此次提交的标识号，便于后续根据该文档id查询该次批量提交的上报情况",<br/>
	"dataType":"ProductPackInfo",<br/>
	"dataList":[<br/>
	{<br/>
	"originNo":"记录的流水号，也就是该记录的id",<br/>
	"productBarCode":"条形码",<br/>
	"createDate":"生产日期",<br/>
	"boxQrCode":"实际箱码",<br/>
	"traceCode":"追溯码",<br/>
	"vBoxQrCode":"虚拟箱码",<br/>
	"factory":"工厂",<br/>
	"station":"产线",<br/>
	"batch":"批次",<br/>
	"shift":"班次"<br/>
	}
	]
	}

	</td>
	</tr>
	</table>
	<p class="font16 mt20 mb10">b) 3. 产品生产追溯信息-产品原料投放信息（ProductMaterialInput）</p>
	<table class="table table-horizontal table-border table-fixed mt10">
	<tr>
	<th>中文名称</th>
	<th>英文名称</th>
	<th>类型</th>
	<th>长度</th>
	<th>是否必填</th>
	<th width='300px'>说明</th>
	</tr>
	<tr>
	<td>流水号</td>
	<td>originNo</td>
	<td>string</td>
	<td>100</td>
	<td>必填</td>
	<td>记录的id</td>
	</tr>
	<tr>
	<td>条形码</td>
	<td>productBarCode</td>
	<td>string</td>
	<td>50</td>
	<td>必填</td>
	<td>按国际标准编制的产品条形码</td>
	</tr>
	<tr>
	<td>生产批次</td>
	<td>produceBatch</td>
	<td>string</td>
	<td>50</td>
	<td>非必填</td>
	<td>产品的生产批次</td>
	</tr>
	<tr>
	<td>生产日期</td>
	<td>produceDate</td>
	<td>string</td>
	<td></td>
	<td>必填</td>
	<td>格式：yyyy-mm-dd</td>
	</tr>

	<tr>
	<td>原料名称</td>
	<td>materialName</td>
	<td>string</td>
	<td>50</td>
	<td>必填</td>
	<td></td>
	</tr>
	<tr>
	<td>原料批次</td>
	<td>batch</td>
	<td>string</td>
	<td>50</td>
	<td>必填</td>
	<td></td>
	</tr>
	<tr>
	<td>原料投放日期	</td>
	<td>createDate</td>
	<td>string</td>
	<td></td>
	<td>必填</td>
	<td>格式：yyyy-mm-dd</td>
	</tr>
	<tr>
	<td>原料生产厂家	</td>
	<td>manufacturer</td>
	<td>string</td>
	<td>255</td>
	<td>必填</td>
	<td></td>
	</tr>
	<tr>
	<td colspan='6' class="text-left">

	{<br/>
	"dataFromSys":"数据来源哪个系统",<br/>
	"sysAccount":"账号",<br/>
	"sysApiKey":"加密账号",<br/>
	"sysApiSecret":"密钥",<br/>
	"documentId":"文档id，唯一性，是此次提交的标识号，便于后续根据该文档id查询该次批量提交的上报情况",<br/>
	"dataType":"ProductMaterialInput",<br/>
	"dataList":[
	{<br/>
	"originNo":"记录的流水号，也就是该记录的id",<br/>
	"materialName":"原料名称",<br/>
	"batch":"原料批次",<br/>
	"manufacturer":"原料生产厂家",<br/>
	"createDate":"原料投放日期",<br/>
	"productBarCode":"产品条形码",<br/>
	"produceDate":"生产日期",<br/>
	"produceBatch":"生产批次"<br/>
	}
	]
	}

	</td>
	</tr>
	</table>
	<p class="font16 mt20 mb10">b) 4.产品生产追溯信息-成品检验扫描件（ProductFinishedCheck）</p>
	<table class="table table-horizontal table-border table-fixed mt10">
	<tr>
	<th>中文名称</th>
	<th>英文名称</th>
	<th>类型</th>
	<th>长度</th>
	<th>是否必填</th>
	<th width='300px'>说明</th>
	</tr>
	<tr>
	<td>流水号</td>
	<td>originNo</td>
	<td>string</td>
	<td>100</td>
	<td>必填</td>
	<td>记录的id</td>
	</tr>
	<tr>
	<td>产品条形码</td>
	<td>productBarCode</td>
	<td>string</td>
	<td>50</td>
	<td>必填</td>
	<td>按国际标准编制的产品条形码</td>
	</tr>
	<tr>
	<td>生产批次</td>
	<td>batch</td>
	<td>string</td>
	<td>50</td>
	<td>非必填</td>
	<td>产品的生产批次</td>
	</tr>
	<tr>
	<td>文件名称</td>
	<td>fileName</td>
	<td>string</td>
	<td>100	</td>
	<td>必填</td>
	<td>上传文件名称（界面显示用），请加上文件的后缀，比如.pdf</td>
	</tr>

	<tr>
	<td>检验报告扫描件</td>
	<td>FILE_CONTENT</td>
	<td>binary</td>
	<td>50</td>
	<td>必填</td>
	<td>Base64编码,pdf文件大小：小于等于300K</td>
	</tr>

	<tr>
	<td colspan='6' class="text-left">

	{<br/>

	"dataFromSys":"数据来源哪个系统",<br/>
	"sysAccount":"账号",<br/>
	"sysApiKey":"加密账号",<br/>
	"sysApiSecret":"密钥",<br/>
	"documentId":"文档id，唯一性，是此次提交的标识号，便于后续根据该文档id查询该次批量提交的上报情况",<br/>
	"dataType":"ProductFinishedCheck",<br/>
	"dataList":[
	{<br/>
	"originNo":"记录的流水号，也就是该记录的id",<br/>
	"productBarCode":"产品条形码",<br/>
	"batch":"生产批次",<br/>
	"fileName":"文件名称",<br/>
	"fileContent":"检验报告扫描件"<br/>
	}
	]
	}
	</td>
	</tr>
	</table>
	<p class="font16 mt20 mb10">b) 5.产品生产追溯信息-采集盐袋数据（SaltBagCollectionData）</p>
	<table class="table table-horizontal table-border table-fixed mt10">
	<tr>
	<th>中文名称</th>
	<th>英文名称</th>
	<th>类型</th>
	<th>长度</th>
	<th>是否必填</th>
	<th width='300px'>说明</th>
	</tr>
	<tr>
	<td>流水号</td>
	<td>originNo</td>
	<td>string</td>
	<td>100</td>
	<td>必填</td>
	<td>记录的id</td>
	</tr>
	<tr>
	<td>盐袋生产日期</td>
	<td>systemDate</td>
	<td>string</td>
	<td>20</td>
	<td>必填</td>
	<td>Yyyy-MM-dd格式</td>
	</tr>
	<tr>
	<td>生产批次</td>
	<td>batch</td>
	<td>string</td>
	<td>50</td>
	<td>非必填</td>
	<td>产品的生产批次</td>
	</tr>
	<tr>
	<td>盐袋二维码</td>
	<td>actualBagId</td>
	<td>string</td>
	<td>50	</td>
	<td>必填	</td>
	<td></td>
	</tr>

	<tr>
	<td>虚拟箱码</td>
	<td>virtualBoxid</td>
	<td>String</td>
	<td>50</td>
	<td>非必填</td>
	<td></td>
	</tr>

	<tr>
	<td colspan='6' class="text-left">

	{<br/>


	"dataFromSys":"数据来源哪个系统",<br/>
	"sysAccount":"账号",<br/>
	"sysApiKey":"加密账号",<br/>
	"sysApiSecret":"密钥",<br/>
	"documentId":"文档id，唯一性，是此次提交的标识号，便于后续根据该文档id查询该次批量提交的上报情况",<br/>
	"dataType":"SaltBagCollectionData",<br/>
	"dataList":[
	{<br/>
	"originNo":"记录的流水号，也就是该记录的id",<br/>
	"systemDate":"日期格式为yyyy-MM-dd",<br/>
	"actualBagId":"盐袋二维码",<br/>
	"virtualBoxid":"虚拟箱码"<br/>
	}
	]
	}

	</td>
	</tr>
	</table>

	<p class="font16 mt20 mb10">c) 销售信息（SaleDetailInfo）</p>
	<table class="table table-horizontal table-border table-fixed mt10">
	<tr>
	<th>中文名称</th>
	<th>英文名称</th>
	<th>类型</th>
	<th>长度</th>
	<th>是否必填</th>
	<th width='300px'>说明</th>
	</tr>
	<tr>
	<td>流水号</td>
	<td>originNo</td>
	<td>string</td>
	<td>100</td>
	<td>必填</td>
	<td>记录的id</td>
	</tr>
	<tr>
	<td>销售单号	</td>
	<td>saleNumber</td>
	<td>string</td>
	<td>50</td>
	<td>非必填</td>
	<td>企业的自由销售单号，有则填写，系统回将同一个单号的内容合并成一个销售单</td>
	</tr>
	<tr>
	<td>销售日期	</td>
	<td>saleDate</td>
	<td>date</td>
	<td>50</td>
	<td>必填</td>
	<td>格式：yyyy-mm-dd</td>
	</tr>
	<tr>
	<td>购货企业名称</td>
	<td>purchaseEnterpriseName</td>
	<td>string</td>
	<td>255	</td>
	<td>必填	</td>
	<td>购货企业在食品流通许可证上的企业名称</td>
	</tr>

	<tr>
	<td>购货企业许可证编号</td>
	<td>purchaseEnterprisePermitNumber</td>
	<td>string</td>
	<td>50</td>
	<td>必填</td>
	<td>购货企业的食品流通许可证编号</td>
	</tr>
	<tr>
	<td>销售人</td>
	<td>managerName</td>
	<td>string</td>
	<td>50</td>
	<td>必填</td>
	<td></td>
	</tr>
	<tr>
	<td>产品条形码</td>
	<td>productBarCode</td>
	<td>string</td>
	<td>50</td>
	<td>非必填</td>
	<td>按国际标准编制的产品条形码</td>
	</tr>
	<tr>
	<td>生产批次</td>
	<td>batch</td>
	<td>string</td>
	<td>50</td>
	<td>非必填</td>
	<td>产品的生产批次</td>
	</tr>
	<tr>
	<td>生产日期</td>
	<td>produceDate</td>
	<td>string</td>
	<td></td>
	<td>必填</td>
	<td>格式：yyyy-mm-dd</td>
	</tr>
	<tr>
	<td>数量</td>
	<td>total</td>
	<td>integer</td>
	<td></td>
	<td>必填</td>
	<td>销售数量</td>
	</tr>
	<tr>
	<td>计量单位</td>
	<td>packUnitName</td>
	<td>string</td>
	<td>50</td>
	<td>必填</td>
	<td>参见附录小包装单位
	</td>
	</tr>
	<tr>
	<td>箱码</td>
	<td>boxCode</td>
	<td>string</td>
	<td>50</td>
	<td>两个必填一个</td>
	<td>符合以下规则的产品购进需上报箱码：
	按箱进货
	</td>
	</tr>
	<tr>
	<td>追溯码</td>
	<td>traceCode</td>
	<td>string</td>
	<td>50</td>
	<td>必填</td>
	<td>符合以下规则的产品购进需上报追溯码：
	按最小包装(如：罐)进货
	</td>
	</tr>
	<tr>
	<td>购货企业所在地区</td>
	<td>purchaseEnterpriseProvince</td>
	<td>string</td>
	<td>50</td>
	<td>必填</td>
	<td></td>
	</tr>
	<tr>
	<td>购货企业所在城市	</td>
	<td>purchaseEnterpriseCity</td>
	<td>string</td>
	<td>50</td>
	<td>必填</td>
	<td></td>
	</tr>
	<tr>
	<td>购货企业详细地址</td>
	<td>purchaseEnterpriseAdress</td>
	<td>string</td>
	<td>255</td>
	<td>必填</td>
	<td></td>
	</tr>
	<tr>
	<td colspan='6' class="text-left">

	{<br/>
	"dataFromSys":"数据来源哪个系统",<br/>
	"sysAccount":"账号",<br/>
	"sysApiKey":"加密账号",<br/>
	"sysApiSecret":"密钥",<br/>
	"documentId":"文档id，唯一性，是此次提交的标识号，便于后续根据该文档id查询该次批量提交的上报情况",<br/>
	"dataType":"SaleDetailInfo",<br/>
	"dataList":[
	{<br/>
	"originNo":"记录的流水号，也就是该记录的id",<br/>
	"saleNumber":"销售单号",<br/>
	"saleDate":"销售日期",<br/>
	"purchaseEnterpriseName":"购货企业名称",<br/>
	"purchaseEnterprisePermitNumber":"购货企业许可证编号",<br/>
	"managerName":"销售人",<br/>
	"contact":"联系方式",<br/>
	"productBarCode":"产品条形码",<br/>
	"batch":"生产批次",<br/>
	"total":"数量",<br/>
	"produceDate":"生产日期",<br/>
	"packUnitName":"计量单位",<br/>
	"boxCode":"箱码",<br/>
	"traceCode":"追溯码",<br/>
	"purchaseEnterpriseProvince":"购货企业所在地区",<br/>
	"purchaseEnterpriseCity":"购货企业所在城市",<br/>
	"purchaseEnterpriseAdress":"购货企业详细地址"<br/>
	}
	]
	}

	</td>
	</tr>
	</table>